services:
  web:
    build: .
    ports: 
      - "80:5000"
    expose:
      - "5000"
    networks:
      - monitoring
  
  prometheus:
    image : prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: midnite
      POSTGRES_USER: midnite_user
      POSTGRES_PASSWORD: midnite_pass
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring

volumes:
  grafana_data:
  postgres_data:

networks:
  monitoring: