global:
  scrape_interval: 5s

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['web:5000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]