name: Deploy to EC2 on push

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull zeusthegoat/midnite-alert-api:latest

            echo "Stopping and removing old container..."
            docker stop midnite-flask-app || true
            docker rm midnite-flask-app || true

            echo "Starting new container..."
            docker run -d \
              --name midnite-flask-app \
              -p 80:5000 \
              zeusthegoat/midnite-alert-api:latest

      - name: Seed database on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd midnite-flask-app
            python3 seed.py
 

            echo "✅ Deploy complete."
