name: Deploy to EC2 on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy Flask app only
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd midnite-flask-app
            echo "Pulling latest changes..."
            git pull origin main

            echo "Building latest Flask app image..."
            docker-compose build web

            echo "Deploying only the Flask app container..."
            docker-compose up -d --no-deps --build web

            echo "✅ Flask app deployment complete."

      - name: Seed database on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd midnite-flask-app
            python3 seed.py
